### ISSUE TITLE
Spreadsheet won't load the document or save changes.

### ISSUE THREAD

**Issue by thecowmilk** [OCA/spreadsheet#41]
## Module
Spreadsheet OCA

## Describe the bug
The bug is that I'd upload the file but when I click on `edit` it won't show the contents. I can edit the content then but when I save the document doesn't save any data/

## To Reproduce
**Affected versions**: 16.0.1.2.4

1. Install the app
2. Open the module
3. Upload a file and then try to edit/view content/save content.

**Expected behavior**
It should display the content of the excel file and save the changes.

**Additional context**
N/A

**Comment by pedrobaeza** [comment]
Excel files can't be "uploaded". There's no such feature. What you upload are the internal JSON definition. Odoo has developed in its library an XLSX import feature, but that's for another higher version.

Closing as no issue, but misunderstanding.

**Comment by thecowmilk** [comment]
I don't know how can you say "there's no such thing as uploading excel files" when literally there's an option to upload. And Second, I noticed the JSON and the structure. Then why is it not saving any Data since there's an option there: File -> Save?!

**Comment by pedrobaeza** [comment]
As said, you can upload JSON files, not Excel files.

**Comment by vdewulf** [comment]
Hello,
@thecowmilk you mention that there is an option to upload an excel file.
Are you referering to this option?
![image](https://github.com/user-attachments/assets/dc5d78b5-48e6-4cb2-b4b8-13ff16553f26)
If yes, this is the standard import option available everywhere on Odoo interface.
That's why @pedrobaeza indicates that there is no upload function in the oca spreadsheet module: there was no dedicated work to make this kind of import work in this context.

I hope this help clarify the situation!
